-- AlterTable
ALTER TABLE "AdvertisementPurchaseSlot" ALTER COLUMN "date" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "anticipatedEndDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PaymentInvoice" ALTER COLUMN "datePaid" SET DATA TYPE TEXT,
ALTER COLUMN "dateSent" SET DATA TYPE TEXT,
ALTER COLUMN "dateDue" SET DATA TYPE TEXT;
